### ISSUE TITLE
License and copyright

### ISSUE THREAD

**Issue by sandrotosi** [stefanholek/conditional#1]
Hi,
in the code there is no information on the copyright years applied to the project, and also the license text is required, since BSD is a too generic name, and the BSD licenses have changed during the years (so you should select one and include the verbatim text somewhere in the source files). These problems prevent the inclusion of this package in Debian

**Comment by sandrotosi** [comment]
any update on this @stefanholek ?

**Comment by stefanholek** [comment]
Fixed in 1.2.
